[project]
name = "service"
version = "0.4.0"
description = "Middleware service"
readme = "readme.md"
requires-python = ">=3.13"
dependencies = [
    "urllib3>=1.26.6",
    "requests>=2.32.5",
    "gunicorn>=23.0.0",
    "flask-cors>=6.0.1",
    "flask>=3.1.2",
    "elasticsearch<9",
]
